version: "1"
services:

  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: react-app
    networks:
      - mern-todo-app-net
    volumes:
      - ./react-app/src:/usr/mern-todo-app/src
      - ./react-app/public:/usr/mern-todo-app/public
    depends_on:
      - node-app
    stdin_open: true
    tty: true

  node-app:
    build:
      context: ./node-app
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    container_name: node-app
    networks:
      - mern-todo-app-net
    volumes:
      - ./node-app/src:/usr/mern-todo-app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-db
    networks:
      - mern-todo-app-net
    volumes:
      - mongo-data:/data/db

networks:
  mern-todo-app-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
